FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:latest-run

COPY . /hound
WORKDIR /hound

RUN go get github.com/hound-search/hound/cmds/... 

# Run the hound
# COPY job /etc/cron.d/job

# Give execution rights on the cron job
# RUN chmod 0644 /etc/cron.d/job

# Apply cron job
# RUN crontab /etc/cron.d/job

CMD ["houndd", "--addr", ":80"]
